/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Legal Literacy for Kids",
  "tagline": "A free, open 18-week curriculum that teaches ages 8–12 how rules, contracts, and legal systems actually work",
  "favicon": "img/favicon.ico",
  "url": "https://literacy-for-kids.github.io",
  "baseUrl": "/legal_literacy_for_kids/",
  "organizationName": "literacy-for-kids",
  "projectName": "legal_literacy_for_kids",
  "deploymentBranch": "gh-pages",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "themes": [
    "literacy-site-theme"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/literacy-for-kids/legal_literacy_for_kids/tree/main/website/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/logo.svg",
    "navbar": {
      "title": "Legal Literacy for Kids",
      "logo": {
        "alt": "Legal Literacy Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "curriculumSidebar",
          "position": "left",
          "label": "Curriculum"
        },
        {
          "type": "dropdown",
          "label": "Literacy for Kids",
          "position": "left",
          "items": [
            {
              "label": "Hub",
              "href": "https://literacy-for-kids.github.io/literacy_for_kids/"
            },
            {
              "label": "Decision",
              "href": "https://literacy-for-kids.github.io/decision_literacy_for_kids/"
            },
            {
              "label": "Computer",
              "href": "https://literacy-for-kids.github.io/computer_literacy_for_kids/"
            },
            {
              "label": "Media",
              "href": "https://literacy-for-kids.github.io/media_literacy_for_kids/"
            },
            {
              "label": "Financial",
              "href": "https://literacy-for-kids.github.io/financial_literacy_for_kids/"
            },
            {
              "label": "Civic",
              "href": "https://literacy-for-kids.github.io/civic_literacy_for_kids/"
            },
            {
              "label": "Emotional & Social",
              "href": "https://literacy-for-kids.github.io/emotional_and_social_literacy_for_kids/"
            },
            {
              "label": "Legal",
              "href": "https://literacy-for-kids.github.io/legal_literacy_for_kids/"
            },
            {
              "label": "Environmental Systems",
              "href": "https://literacy-for-kids.github.io/environmental_system_literacy/"
            },
            {
              "label": "Health Systems",
              "href": "https://literacy-for-kids.github.io/health_literacy_for_kids/"
            }
          ]
        },
        {
          "href": "https://github.com/literacy-for-kids/legal_literacy_for_kids",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Literacy for Kids",
          "items": [
            {
              "label": "Project Hub",
              "href": "https://literacy-for-kids.github.io/literacy_for_kids/"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/literacy-for-kids"
            }
          ]
        },
        {
          "title": "Curricula",
          "items": [
            {
              "label": "Decision Literacy",
              "href": "https://literacy-for-kids.github.io/decision_literacy_for_kids/"
            },
            {
              "label": "Computer Literacy",
              "href": "https://literacy-for-kids.github.io/computer_literacy_for_kids/"
            },
            {
              "label": "Media Literacy",
              "href": "https://literacy-for-kids.github.io/media_literacy_for_kids/"
            },
            {
              "label": "Financial Literacy",
              "href": "https://literacy-for-kids.github.io/financial_literacy_for_kids/"
            },
            {
              "label": "Civic Literacy",
              "href": "https://literacy-for-kids.github.io/civic_literacy_for_kids/"
            }
          ]
        }
      ],
      "copyright": "Literacy for Kids — open-source curricula for children ages 8–12"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": []
  },
  "baseUrlIssueBanner": true,
  "storage": {
    "type": "localStorage",
    "namespace": false
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false,
      "siteStorageNamespacing": false,
      "fasterByDefault": false,
      "mdx1CompatDisabledByDefault": false
    },
    "faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false,
      "gitEagerVcs": false
    },
    "experimental_vcs": {},
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
